In [1]:
! pip install numpy


In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
print("hello")
"jihgfhjkl"

hello


'jihgfhjkl'

In [4]:
print("hello")

hello


In [5]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np ##as is a keyword used to create shorter(alias) nickname to lirary


In [7]:
np.__version__

'2.4.6'

In [8]:
lst=list([1,2,3,4,5,6])
arr =np.array(lst)

In [9]:
lst
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
type(arr)

numpy.ndarray

In [11]:
lst=list(range(1,10)) ##creating list using range function
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
arr=np.array([1,2,3,4,5,6,7]) ###to convert list into array

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
arr=np.array([range(1,20)])
arr


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]])

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr=np.arange(1,20) ###use of range function in array

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
lst=list(range[1,20]) ###erroe because im using this bracket[] instead of ()

TypeError: type 'range' is not subscriptable

In [ ]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros((1,20))

In [ ]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
arr=np.ones((1,20))

In [ ]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [ ]:
arr=np.zeros((5,20)) ##to print zero matrix we are using zeros
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
print(arr.ndim) ##ndim for checking dimensions of array

2


In [ ]:
arr=np.linspace(1,10,5) ## this function is used togenerate numeric sequences based on 3 main parameters 
####*start(1):starting value of sequence 
# *end(10): end value of sequence
# num(5):the total number of samples to generates 
print(arr)
print(type(arr))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [ ]:
arr=np.linspace(3,10,5)

In [ ]:
arr

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [ ]:
arr=np.zeros((5,20))

In [ ]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
arr=np.arange([1,20]) ##error because only small bracket is used()

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [ ]:
arr=np.arange(1,20) 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
arr=np.arange(0,30)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr=arr.reshape(10,3) ###ir changes 1D array into 2d array
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
arr=arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
arr=arr.reshape(3,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr=np.random.randint(1,5,10) ###for generating random array in given ()
## start(1):starting point of array
## end(5):end of aray
#### num(10):no. of items we want in your array

In [ ]:
arr

array([3, 3, 4, 2, 2, 2, 3, 2, 4, 3], dtype=int32)

In [ ]:
arr=np.random.randint(1,5,(5,6)) ###to create random 2D array
arr

array([[3, 3, 4, 2, 4, 1],
       [1, 4, 4, 3, 4, 1],
       [1, 4, 3, 1, 4, 4],
       [4, 4, 1, 4, 4, 2],
       [1, 2, 2, 2, 4, 3]], dtype=int32)

In [ ]:
arr=np.random.random(10) ##for generating random num(10) items 
arr

array([0.35082229, 0.18424986, 0.5270433 , 0.3479455 , 0.86578999,
       0.84650774, 0.75683915, 0.64718235, 0.37826644, 0.11126081])

In [ ]:
np.random.random((10,3)) ###random 2D  array generated 

array([[0.24778007, 0.61129469, 0.07793561],
       [0.08139174, 0.22339341, 0.47245261],
       [0.67535483, 0.94391854, 0.13986637],
       [0.49335755, 0.98197157, 0.44063278],
       [0.93968113, 0.2845369 , 0.37711285],
       [0.31032113, 0.21426204, 0.56231687],
       [0.60992441, 0.02553059, 0.48574816],
       [0.17850095, 0.3311094 , 0.34225644],
       [0.65979394, 0.0694382 , 0.11503526],
       [0.16854497, 0.80292071, 0.54850666]])

In [ ]:
arr=np.arange(60).reshape(12,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
### attributes of array:-
print("no. of dim:",arr.ndim) 
print("sixe of array",arr.size)
print("data type of item in array: ",arr.dtype)
print("shape of array",arr.shape)

no. of dim: 2
sixe of array 60
data type of item in array:  int64
shape of array (12, 5)


In [ ]:
lst=[[1,2,3],[4,5,6]] ###creating 2D list
lst

[[1, 2, 3], [4, 5, 6]]

In [ ]:
arr=np.array(lst) ###creating 2D Array

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr[0,0] ###indexing and slicing

np.int64(0)

In [ ]:
arr[0][0]

np.int64(0)

In [ ]:
arr[11,4]

np.int64(59)

In [ ]:
arr[-1,-1]

np.int64(59)

In [ ]:
arr[11,-1]

np.int64(59)

In [ ]:
arr[11][4]

np.int64(59)

In [ ]:
arr[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr[9:11,1:3]

array([[46, 47],
       [51, 52]])

In [ ]:
arr[5:7,3:5]

array([[28, 29],
       [33, 34]])

In [ ]:
arr[0:10,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48]])

In [ ]:
arr[-1]


np.int64(7)

In [ ]:
arr.T  ###transpose

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [ ]:
arr.transpose() ##for transpose

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr.shape

(12, 5)

In [ ]:
arr.size

60

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

2

* 3D array

In [ ]:
arr=np.arange(225).reshape(5,15,3) 
#start(5): no. of tables
#mid(15):no. of rows in each table
#end(3):no of columns in each table
#5,15,3=5*15*5=225


In [ ]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [ ]:
arr[0] #for first table

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [ ]:
arr[0][0] ##for first row of first table

array([0, 1, 2])

In [ ]:
arr[0][0][0] #for first element of table

np.int64(0)

In [ ]:
arr[-1] ##for last table

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [ ]:
arr[2] ##3rd table of array

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [ ]:
arr[0][0]

array([0, 1, 2])

In [ ]:
arr[1][1]

array([48, 49, 50])

In [ ]:
arr[0:5,0] ##for first row of each table

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [ ]:
arr[0:5,0,0] ##first element of each table

array([  0,  45,  90, 135, 180])

In [ ]:
arr[0:5,-1] ##last row of each table

array([[ 42,  43,  44],
       [ 87,  88,  89],
       [132, 133, 134],
       [177, 178, 179],
       [222, 223, 224]])

In [ ]:
arr[0:5,-1,-1] ##fo

array([ 44,  89, 134, 179, 224])

In [ ]:
arr[0:5,2:4]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [ ]:
arr[0:5,:,1:3]

array([[[  1,   2],
        [  4,   5],
        [  7,   8],
        [ 10,  11],
        [ 13,  14],
        [ 16,  17],
        [ 19,  20],
        [ 22,  23],
        [ 25,  26],
        [ 28,  29],
        [ 31,  32],
        [ 34,  35],
        [ 37,  38],
        [ 40,  41],
        [ 43,  44]],

       [[ 46,  47],
        [ 49,  50],
        [ 52,  53],
        [ 55,  56],
        [ 58,  59],
        [ 61,  62],
        [ 64,  65],
        [ 67,  68],
        [ 70,  71],
        [ 73,  74],
        [ 76,  77],
        [ 79,  80],
        [ 82,  83],
        [ 85,  86],
        [ 88,  89]],

       [[ 91,  92],
        [ 94,  95],
        [ 97,  98],
        [100, 101],
        [103, 104],
        [106, 107],
        [109, 110],
        [112, 113],
        [115, 116],
        [118, 119],
        [121, 122],
        [124, 125],
        [127, 128],
        [130, 131],
        [133, 134]],

       [[136, 137],
        [139, 140],
        [142, 143],
        [145, 146],
        [148, 

In [ ]:
arr[0:5,-1,-1] #for last element of each table

array([ 44,  89, 134, 179, 224])

In [ ]:
arr[0:5,0:1,0:1] ##first row and column of each table

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [ ]:
print("shape:",arr.shape)
print("size",arr.size)
print("datatype",arr.dtype)
print("dimension",arr.ndim)

shape: (5, 15, 3)
size 225
datatype int64
dimension 3


In [ ]:
arr[0,0,0]=100 #first element of first row of first table
arr

array([[[100,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [ ]:
arr[0:5,0]=100 ##all first row of each table is repalced by 100
arr

array([[[100, 100, 100],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[100, 100, 100],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[100, 100, 100],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [ ]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [ ]:
arr1=np.array([1,30,45,0])
arr2=np.array([23,45,6,9])
print("array1:",arr1)
print("array2",arr2)


array1: [ 1 30 45  0]
array2 [23 45  6  9]


In [ ]:
arr1=np.array([1,30,45,0])
arr1.sort()
print(arr1)
arr2=np.array([23,45,6,9])
arr2.sort()
print(arr2)


[ 0  1 30 45]
[ 6  9 23 45]


* conversion of 3D array into 1D aaray

In [ ]:
arr=np.arange(225)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
arr=arr.reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11